name: Build IPA from uploaded file

on:
  push:
    paths:
      - 'input/*.ipa'
  workflow_dispatch:

env:
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v5
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Install tools
        run: |
          brew install make dpkg ldid
          python3 -m pip install --break-system-packages git+https://github.com/asdfzxcvbn/pyzule-rw.git

      - name: Prepare IPA from repository
        run: |
          mkdir -p ipa
          # Nimmt die erste IPA-Datei aus dem input/-Ordner
          IPA_PATH=$(find input -name "*.ipa" | head -n 1)
          if [ -z "$IPA_PATH" ]; then
            echo "::error::Keine IPA-Datei im Ordner 'input/' gefunden."
            exit 1
          fi
          cp "$IPA_PATH" ipa/spotify.ipa
          case "$(file --mime-type -b ipa/spotify.ipa)" in application/zip|application/x-ios-app) ;; *) echo "::error::Not an IPA"; exit 1 ;; esac

      - run: make release

      - uses: actions/upload-artifact@v5
        with:
          name: spoti.ipa
          path: out/*.ipa
          if-no-files-found: error
